[build]
  command = ""       # no build step because it's a static site
  publish = "."      # your index.html is in the root directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
